name: Audit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '15 23 * * 0'

jobs:
  audit:
    runs-on: ubuntu-latest
    name: audit check
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - run: npm run audit
