name: Audit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '15 23 * * 0'

jobs:
  audit:
    runs-on: ubuntu-latest
    name: audit check
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.19
      - run: pnpm audit
