name: Codecov

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci && npm run build
      - run: npm run start-devnet
      - run: npm run test
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          name: codecov-alephium-web3
          fail_ci_if_error: true
