name: Unit Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: lerna bootstrap --hoist
      # - run: npm install @jest/types --save-dev
      # - run: npm run check-versions
      - run: lerna run lint
      - run: lerna exec -- npm audit --production
      - run: lerna run start-devnet
      - run: lerna run test
